CREATE DATABASE IF NOT EXISTS CRUDStudents;
CREATE DATABASE IF NOT EXISTS CRUDEmployeeemployee;
CREATE DATABASE IF NOT EXISTS ContactBook;
CREATE DATABASE IF NOT EXISTS UsersSpringS;
CREATE DATABASE IF NOT EXISTS ProductApp;
CREATE DATABASE IF NOT EXISTS InventoryManagementApp; 